### ISSUE TITLE
Finding Swig on Windows

### ISSUE THREAD

**Issue by luciansmith** [NuML/NuML#1]
CMake couldn't find Swig on my system, but it's where Swig now normally installs:  C:/Program Files (x86)/Swig/swig.exe

**Comment by fbergmann** [comment]
I wonder how this is different from libSBML does libSBML find your swig by default? thanks!

**Comment by luciansmith** [comment]
It does, but I changed CMakeLists.txt myself so that it would, IIRC.

**Comment by fbergmann** [comment]
now fixed in master will be in the next release
