### ISSUE TITLE
example needed for adding metadata ...

### ISSUE THREAD

**Issue by fbergmann** [NuML/NuML#10]
vincent told me that there would be an issue adding metadata to numl documents.

**Comment by hsauro** [comment]
That's a bit of a problem.....

Herbert

**Comment by fbergmann** [comment]
this should now work the isset / get / set  functions for notes and annotations are present. I've removed the CVterms list, as that one is provided by the RDFParser from the libSBML library. I hope that solves the issue.

**Comment by fbergmann** [comment]
this has been resolved
