### ISSUE TITLE
Parser expects <resultComponents> tag which is not defined in spec

### ISSUE THREAD

**Issue by matthiaskoenig** [NuML/NuML#11]
libnuml expects an outer `resultComponents` tag in the numl files which is not defined in the spec.
I.e. NuML files with
```
<resultComponents>
  <resultComponent id="id1">
   ...
  </resultComponent>
</resultComponents>
``` 
can be parsed (example oscli.numl), but the spec states that numl files have to be
```
  <resultComponent id="id1">
   ...
  </resultComponent>
```
If files are according to spec they fail to parse (example oscli2.numl)

[examples.zip](https://github.com/NuML/NuML/files/1333274/examples.zip)

```
OSError: NUML ERROR in './examples/./oscli2.numl': line 178: (10102 [Error]) An NUML XML document must not contain undefined elements or attributes in the NUML namespace. Documents containing unknown elements or attributes placed in the NUML namespace do not conform to the NUML specification. (References: L2V2 Section 4.1; L2V3 Section 4.1; L2V4 Section 4.1) Element 'resultComponent' is not part of the definition of NUML Level 1 Version 1.
```

Workaround:
- create invalid numl files with `<resultComponents>` tag

**Comment by fbergmann** [comment]
good point ... this will have to wait for a bit to figure out what the correct thing to do here is ... I will try to reach the authors of the spec to sort what ought to change ...

**Comment by fbergmann** [comment]
This should now be resolved in master, do you need me to do a new pypi release?

**Comment by matthiaskoenig** [comment]
This would be great. Makes it much easier for me to test and use in CI. 
Thanks for that.
