### ISSUE TITLE
Python bindings: Request for PYTHON_USE_DYNAMIC_LOOKUP build flag

### ISSUE THREAD

**Issue by 0u812** [NuML/NuML#12]
Hi Frank! As with [other projects](https://sourceforge.net/p/sbml/libsbml/430/), I was wondering if you could add a PYTHON_USE_DYNAMIC_LOOKUP build flag to libNuML. If you could implement the flag like in [libsbml](https://sourceforge.net/p/sbml/libsbml/430/) and libSEDML, that would be great. Just for reference, here is a reiteration of the requirements that I requested for libsbml and libSEDML:

* On Windows, no change is required - you can link to the Python libraries [as you currently do](https://github.com/NuML/NuML/blob/master/libnuml/src/bindings/python/CMakeLists.txt#L128):
```
target_link_libraries(binding_python_lib ${LIBNUML_LIBRARY}-static ${PYTHON_LIBRARIES})
```
* On Linux and Mac (when the flag is enabled), please do not link to the Python libraries:
```
target_link_libraries(binding_python_lib ${LIBNUML_LIBRARY}-static)
```
* Additionally, on Mac only, please add the following link flags:
```
set_target_properties (binding_python_lib PROPERTIES LINK_FLAGS "-undefined dynamic_lookup")
```

Sourceforge seems to be down right now, so the link I posted above doesn't work, but it will hopefully be back online when you read this. Please let me know if anything isn't clear.

**Comment by matthiaskoenig** [comment]
This is the remaining issue for SED-ML L1V3 in tellurium. I have all the NuML parsing and plotting data implemented in isolation. The problem is to now get the functionality in tellurium. This would allow Kyle to build the tenuml package, so I can include the numl functionality.

**Comment by 0u812** [comment]
Thanks Frank!
