### ISSUE TITLE
Python interpreter dies when parsing DimensionDescription on DataDescription

### ISSUE THREAD

**Issue by matthiaskoenig** [NuML/NuML#16]
When trying to parse the DimensionDescription on a dataDescription the python interpreter dies.
Parsing the DimensionDescription on a numl ResultComponent works without problems.

I attached an example which show the problem. It looks like the size of the description is not set and consequently one iterateres over memory areas which one shouldn't
I get a description.size() of 3929155189

```
/home/mkoenig/envs/tellurium/bin/python /home/mkoenig/git/tellurium/tellurium/dev/oven/libnuml_dd_139error.py
parseDataDescriptions: reading-numlData1D.xml
<tenuml.libnuml.DimensionDescription; proxy of <Swig Object of type 'DimensionDescription *' at 0x7fa8b3b18840> >
parse_dimension_description: <tenuml.libnuml.DimensionDescription; proxy of <Swig Object of type 'DimensionDescription *' at 0x7fa8b3b18840> >
3929155189

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```
This only affects the DimensionDescription on the DataDescription in SED-ML.

[139_example.zip](https://github.com/NuML/NuML/files/1359516/139_example.zip)

M

**Comment by fbergmann** [comment]
this works on my end and yields: 

```
parseDataDescriptions: reading-numlData1D.xml
<DimensionDescription[1]>
parse_dimension_description: <DimensionDescription[1]>
1
typecode: 14
        * CompositeDescription: {'SpeciesIds': 'string'}
typecode: 16
        * AtomicDescription: {'': 'double'}
[{'SpeciesIds': 'string'}, {'': 'double'}]
```

what system are you using?

**Comment by fbergmann** [comment]
also I guess I need to know what python interpreter you are using to cause this issue :)

**Comment by matthiaskoenig** [comment]
Good point. 

I looked into it and found that this is not a libnuml issue, but the problem is that tenuml was updated, but tesedml not yet. So the versions don't work together, i.e. the tenuml in tesedml is not fitting with tenuml.

```
# mkvirtualenv test139 -p python3.5
# (test139) python ./libnuml_dd_139error.py

# These dependencies work:
python-libnuml>=1.1.1
python-libsedml>=0.4.3

# These dependencies work not
tenuml>=1.1.1
tesedml>=0.4.2
```

I attached a full example with the requirements
[example139.zip](https://github.com/NuML/NuML/files/1359881/example139.zip)

@0u812 This is your issue and is solved by updateing tesedml with the latest code
https://github.com/sys-bio/tellurium/issues/231

**Comment by fbergmann** [comment]
In that case it is actually working as intended, the swig version of the wrapper and the symbols of the c++ library need to be of the same version otherwise stuff will break, that is only to be expected. Sorry for the inconvenience ...

**Comment by matthiaskoenig** [comment]
Fixed via update of tesedml. 
thanks @0u812
