### ISSUE TITLE
Include error while building python bindings

### ISSUE THREAD

**Issue by vincent-noel** [NuML/NuML#17]
Hi Frank,

I have an error while building the python bindings from the latest commits : 

> /root/builds/NuML/libnuml/src/bindings/python/../swig/libnuml.i:77: Error: Unable to find 'numl/common/libnuml-namespace.h'

Pointing to the proper directory in libnuml.i, by replacing 

> %import  numl/common/libnuml-namespace.h

with 

> %import  ../../numl/common/libnuml-namespace.h

works fine in my case. Not sure it's a proper fix thought.

Hope you guys are having a good COMBINE meeting.
Cheers

**Comment by fbergmann** [comment]
Thanks for letting me know, this must have gotten broken when applying a pull request last week. It will be fixed now ... 

And yes, COMBINE is going strong :) ... too bad you could not make it ... 
cheers

**Comment by vincent-noel** [comment]
Working now !

Thanks
