### ISSUE TITLE
Build failure on mac

### ISSUE THREAD

**Issue by luciansmith** [NuML/NuML#18]
On Catalina, with the latest XCode, libnuml fails to link:

[  2%] Linking CXX shared library libnuml.dylib
cd /Users/lpsmith/libnuml/build-release/src && /Applications/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/numl.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 1.0.0 -current_version 1.1.1 -o libnuml.1.1.1.dylib -install_name /Users/lpsmith/libnuml/build-release/src/libnuml.1.dylib CMakeFiles/numl.dir/numl/common/libnuml-version.cpp.o CMakeFiles/numl.dir/numl/AtomicDescription.cpp.o CMakeFiles/numl.dir/numl/AtomicValue.cpp.o CMakeFiles/numl.dir/numl/CompositeDescription.cpp.o CMakeFiles/numl.dir/numl/CompositeValue.cpp.o CMakeFiles/numl.dir/numl/Dimension.cpp.o CMakeFiles/numl.dir/numl/DimensionDescription.cpp.o CMakeFiles/numl.dir/numl/NMBase.cpp.o CMakeFiles/numl.dir/numl/NUMLConvert.cpp.o CMakeFiles/numl.dir/numl/NUMLDocument.cpp.o CMakeFiles/numl.dir/numl/NUMLError.cpp.o CMakeFiles/numl.dir/numl/NUMLErrorLog.cpp.o CMakeFiles/numl.dir/numl/NUMLList.cpp.o CMakeFiles/numl.dir/numl/NUMLNamespaces.cpp.o CMakeFiles/numl.dir/numl/NUMLReader.cpp.o CMakeFiles/numl.dir/numl/NUMLTypeCodes.cpp.o CMakeFiles/numl.dir/numl/NUMLVisitor.cpp.o CMakeFiles/numl.dir/numl/NUMLWriter.cpp.o CMakeFiles/numl.dir/numl/OntologyTerm.cpp.o CMakeFiles/numl.dir/numl/ResultComponent.cpp.o CMakeFiles/numl.dir/numl/Tuple.cpp.o CMakeFiles/numl.dir/numl/TupleDescription.cpp.o  /usr/local/lib/libsbml-static.a /usr/lib/libbz2.dylib /usr/lib/libz.dylib /usr/lib/libxml2.dylib 
duplicate symbol 'Dimension::clone() const' in:
    CMakeFiles/numl.dir/numl/Dimension.cpp.o
    /usr/local/lib/libsbml-static.a(Dimension.cpp.o)
duplicate symbol 'Dimension::getElementName() const' in:
    CMakeFiles/numl.dir/numl/Dimension.cpp.o
    /usr/local/lib/libsbml-static.a(Dimension.cpp.o)
duplicate symbol 'Dimension::getTypeCode() const' in:
    CMakeFiles/numl.dir/numl/Dimension.cpp.o
    /usr/local/lib/libsbml-static.a(Dimension.cpp.o)
duplicate symbol 'Dimension::~Dimension()' in:
    CMakeFiles/numl.dir/numl/Dimension.cpp.o
    /usr/local/lib/libsbml-static.a(Dimension.cpp.o)
duplicate symbol 'Dimension::~Dimension()' in:
    CMakeFiles/numl.dir/numl/Dimension.cpp.o
    /usr/local/lib/libsbml-static.a(Dimension.cpp.o)
duplicate symbol 'Dimension::~Dimension()' in:
    CMakeFiles/numl.dir/numl/Dimension.cpp.o
    /usr/local/lib/libsbml-static.a(Dimension.cpp.o)
duplicate symbol 'vtable for Dimension' in:
    CMakeFiles/numl.dir/numl/Dimension.cpp.o
    /usr/local/lib/libsbml-static.a(Dimension.cpp.o)
duplicate symbol 'typeinfo name for Dimension' in:
    CMakeFiles/numl.dir/numl/Dimension.cpp.o
    /usr/local/lib/libsbml-static.a(Dimension.cpp.o)
duplicate symbol 'typeinfo for Dimension' in:
    CMakeFiles/numl.dir/numl/Dimension.cpp.o
    /usr/local/lib/libsbml-static.a(Dimension.cpp.o)
ld: 9 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by luciansmith** [comment]
Actually, I get similar errors in Visual Studio:

2>libsbml-static.lib(Dimension.obj) : error LNK2005: "public: __cdecl Dimension::Dimension(class Dimension const &)" (??0Dimension@@QEAA@AEBV0@@Z) already defined in AtomicDescription.obj
2>libsbml-static.lib(Dimension.obj) : error LNK2005: "public: class Dimension & __cdecl Dimension::operator=(class Dimension const &)" (??4Dimension@@QEAAAEAV0@AEBV0@@Z) already defined in AtomicDescription.obj
2>libsbml-static.lib(Dimension.obj) : error LNK2005: "public: virtual class Dimension * __cdecl Dimension::clone(void)const " (?clone@Dimension@@UEBAPEAV1@XZ) already defined in Dimension.obj
2>libsbml-static.lib(Dimension.obj) : error LNK2005: "public: virtual __cdecl Dimension::~Dimension(void)" (??1Dimension@@UEAA@XZ) already defined in Dimension.obj
2>libsbml-static.lib(Dimension.obj) : error LNK2005: "public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __cdecl Dimension::getElementName(void)const " (?getElementName@Dimension@@UEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) already defined in Dimension.obj

**Comment by fbergmann** [comment]
It does not do that for me ... so that must mean that you are linking in another package that also defines a `Dimension` class. I'm not sure what to do about that one. Let me know what packages you are linking for libSBML and hopefully they are not finalized, so that we can rename the class there. Otherwise your only chance is to build libNUML with namespaces enabled.

**Comment by luciansmith** [comment]
Ah!  That would be the 'Arrays' package, then.  I would not suggest renaming that class, which means using the libsbml or numl namespace (or both) enabled.

**Comment by fbergmann** [comment]
Right, but given, that Arrays is not finalized yet, it could easily have an `ArrayDimension` class, rather than `Dimension` ... but sure ... for now if you use namespaces you'll be good.

**Comment by fbergmann** [comment]
closing this for now, as namespaces do provide a workaround, and the hope is when / if there is a final arrays package it uses another name.
