### ISSUE TITLE
C++ Namespace

### ISSUE THREAD

**Issue by 0u812** [NuML/NuML#2]
It's not clear to me why there is a flag for C++ namespaces. LibSBML also has such a flag, but in that case the flag is for compatibility with software that was written before libSBML corrected the mistake of not having a namespace. This project looks much newer so I don't understand the need for such a flag.

In any case, the flag should be on by default. Novice programmers won't know to turn it off and will consequently write bad code which doesn't follow best practices of using namespaces (I actually made that very mistake when learning libSBML and I'd like to prevent others from making the same mistake).

**Comment by nickerso** [comment]
I think this is a consequence of using the libSBML XML schema -> code generation to create the initial API code. You can also see this in the libSED-ML C++ code which started the same way. 

I agree that it should be set to on by default.

**Comment by fbergmann** [comment]
the reason there is such a flag, is that people can decide whether they want the namespace to be enabled or not. 

I disagree that it should be enabled by default, as it would cause issues for namespace aware language bindings, and it would truly lead to a nightmare where each of them would look different. 

I don't think it is too onerous to flick the flag if you need to.
