### ISSUE TITLE
Cannot build with namespace-enabled libSBML

### ISSUE THREAD

**Issue by 0u812** [NuML/NuML#3]
While trying to build libsedml against a C++ namespace-enabled version of libsbml, I ran into errors generated by the libnuml due to not being able to find certain libsbml symbols behind the libsbml namespace. Please see fbergmann/libSEDML#26 for details.

**Comment by fbergmann** [comment]
hello Kyle, 

could you try the latest commit? I think it will solve the issue ... if it does I can make a new release. 

thanks
Frank

**Comment by 0u812** [comment]
Yes, I just tried the latest commit (0e34663a67a5fd035fc951f48be081495b957246) and it works. Thanks so much!
