### ISSUE TITLE
Issue with SWIG complaining with line indentation

### ISSUE THREAD

**Issue by kirichoi** [NuML/NuML#4]
Using SWIG 3.0.10 results error while building Python bindings on VS2013.

This is caused by line 705 in [src/bindings/python/local.i](https://github.com/NuML/NuML/blob/master/libnuml/src/bindings/python/local.i)

Adding few spaces solves the issue.

**Comment by matthiaskoenig** [comment]
@kirichoi I just run into the same issue and created a pull request for this.

**Comment by fbergmann** [comment]
this has been resolved
